### ISSUE TITLE
Unable to build any examples (out of box) either on emulator or with board.

### ISSUE THREAD

**Issue by ydigikat** [theembeddedrustacean/ser-no-std#1]
**Describe the error**
The learning examples in the book do not build (at least for me).  Seems there has been an evolution of the framework since these were created however there appears to be no updates to the book.  This is true for both local and Wokwi builds, the initial template on Wokwi will not rebuild as soon as any changes are made.  

**Error Location**
Blinky example.  The same problem on both the emulator and local build.  

Obviously the dependencies have changed, but simply updating to later versions introduces further problems.

**Screenshots**

Code from book (dependency problem):

![image](https://github.com/user-attachments/assets/899fbcc5-b33c-436f-b92c-e8568774e239)

Cargo-generated template (works, later versions):

![image](https://github.com/user-attachments/assets/46a6cca0-3aa7-4fd3-a869-62b7aa6374b7)

Back-porting code from book fails to build:

![image](https://github.com/user-attachments/assets/2b15bfca-ac5f-4724-a296-04781dbb0b91)

Further changes to try to fix problems result in a errors relating to renamed or missing methods, at which point I gave up.

I am a experienced C engineer looking (I confess, somewhat reluctantly) to investigate embedded Rust for my organisation and no doubt I would be able to fix these problems by wading through ESP documentation.  I purchased the book to  hopefully shortcut the need for having to do too much of this.  

Hopefully you can provide some guidance and reassurance that the book is being maintained as advertised :)

**Comment by theembeddedrustacean** [comment]
Thank you for reporting. Yes, these errors are happening due to the version updates of both the crates and the builder. An updated book version is being worked on and will be released in the upcoming couple of weeks.

**Comment by ydigikat** [comment]
That is good news!  I shall set things aside until that is complete, I'd rather be able to work through the material as intended without having to fix up problems.

**Comment by theembeddedrustacean** [comment]
Closing issue. The repos have been updated to fix the issue. Both the book and repos have been updated to support the latest crate and compiler versions. Web-based Wokwi might still not be up to speed, but it's a matter of time until it's updated to the latest.
